name: Convert latest fp-ts release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setup Node.js environment
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc

      - name: Download the latest fp-ts release from npm
        run: npm pack fp-ts

      - name: Extract the tarball
        run: tar -xzvf *.tgz
        
      - name: Make a build directory
        run: mkdir -v build
          
      - name: Copy the es6 folder from package
        run: cp -v -r ./package/es6 ./build/esm
        
      - name: Copy HKT.d.ts from package
        run: cp -v ./package/HKT.d.ts ./build/esm/HKT.d.ts

      - name: Copy package.json from package
        run: cp -v ./package/package.json ./build/
        
      - name: Move ./build/esm/HKT/index.js to ./build/esm/HKT.js
        run: mv -v ./build/esm/HKT/index.js ./build/esm/HKT.js
        
      - name: Remove the ./build/esm/HKT directory.
        run: rm -vrf ./build/esm/HKT
